#version 450

layout(local_size_x = 8, local_size_y = 8) in;

#include "functions.glsl"

layout (set = 0, binding = 0, rgba32f) uniform writeonly image2D transmittance_lut;

void main(){
    AtmosphereParameters atmosphere = GetAtmosphereParameters();

    vec3 transimittance = ComputeTransmittanceToTopAtmosphereBoundaryTexture(atmosphere, gl_GlobalInvocationID.xy + vec2(0.5));
    imageStore(transmittance_lut, ivec2(gl_GlobalInvocationID.xy), vec4(transimittance, 1.0));
}

