#pragma once

#ifndef PLATFORM_SUPPORT_SSE3_INTRINSICS
#define PLATFORM_SUPPORT_SSE3_INTRINSICS false
#endif

#define USE_ROW_MAJOR_MATRIX true

#define USE_RIGHT_HAND_COORD true

#define ENABLE_SHADER_DEBUG_MARKER