# APPLICATION Files

set(APPLICATION_INTERFACE_DIR ${ENGINE_RUNTIME_SOURCE_DIR}/Application/Public)
set(APPLICATION_SOURCE_DIR ${ENGINE_RUNTIME_SOURCE_DIR}/Application/Private)

file(GLOB_RECURSE APPLICATION_INTERFACE_FILES ${APPLICATION_INTERFACE_DIR}/Application/*.h ${APPLICATION_INTERFACE_DIR}/Application/*.hpp)
file(GLOB_RECURSE APPLICATION_INCLUDE_FILES ${APPLICATION_SOURCE_DIR}/*.h PREFIX "Header" ${APPLICATION_SOURCE_DIR}/*.hpp)
file(GLOB_RECURSE APPLICATION_SOURCE_FILES ${APPLICATION_SOURCE_DIR}/*.cpp "Source" ${APPLICATION_SOURCE_DIR}/**.c)
