#RESOURCES Files

set(RESOURCES_INTERFACE_DIR ${ENGINE_RUNTIME_SOURCE_DIR}/RESOURCES/Public)
set(RESOURCES_SOURCE_DIR ${ENGINE_RUNTIME_SOURCE_DIR}/RESOURCES/Private)


file(GLOB_RECURSE RESOURCES_INTERFACE_FILES ${RESOURCES_INTERFACE_DIR}/Resources/*.h ${RESOURCES_INTERFACE_DIR}/Resources/*.hpp)
file(GLOB_RECURSE RESOURCES_INCLUDE_FILES ${RESOURCES_SOURCE_DIR}/*.h PREFIX "Header" ${RESOURCES_SOURCE_DIR}/*.hpp)
file(GLOB_RECURSE RESOURCES_SOURCE_FILES ${RESOURCES_SOURCE_DIR}/*.cpp "Source" ${RESOURCES_SOURCE_DIR}/**.c)

