function(horizon_group_slang_targets directory)
    get_property(targets DIRECTORY "${directory}" PROPERTY BUILDSYSTEM_TARGETS)
    foreach(target IN LISTS targets)
        get_target_property(folder ${target} FOLDER)
        set(group "Horizon/ThirdParty/Slang")
        if(folder)
            string(APPEND group "/${folder}")
        endif()
        set_target_properties(${target} PROPERTIES FOLDER "${group}")
    endforeach()
    get_property(subdirectories DIRECTORY "${directory}" PROPERTY SUBDIRECTORIES)
    foreach(subdirectory IN LISTS subdirectories)
        horizon_group_slang_targets("${subdirectory}")
    endforeach()
endfunction()

function(horizon_add_slang)
    foreach(feature GFX SLANG_RHI SLANGD SLANGC SLANGI SLANGRT SLANG_GLSLANG SLANG_PROXY
                    TESTS EXAMPLES REPLAYER CUDA OPTIX NVAPI AFTERMATH MIMALLOC)
        set(SLANG_ENABLE_${feature} OFF)
    endforeach()
    set(SLANG_EXCLUDE_DAWN ON)
    set(SLANG_EXCLUDE_TINT ON)
    set(SLANG_SLANG_LLVM_FLAVOR DISABLE)
    set(SLANG_LIB_TYPE SHARED)
    if(MSVC)
        string(APPEND CMAKE_C_FLAGS " /utf-8")
        string(APPEND CMAKE_CXX_FLAGS " /utf-8")
    endif()
    add_subdirectory(${ENGINE_THIRD_PARTY_SOURCE_DIR}/slang ${CMAKE_BINARY_DIR}/slang EXCLUDE_FROM_ALL)
    if(MSVC AND CMAKE_GENERATOR MATCHES "Visual Studio")
        target_compile_options(slang-common-objects PRIVATE /MP)
    endif()
    horizon_group_slang_targets("${ENGINE_THIRD_PARTY_SOURCE_DIR}/slang")
endfunction()

horizon_add_slang()
